apiVersion: apps/v1
kind: Deployment
metadata:
  name: aahar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aahar
  template:
    metadata:
      labels:
        app: aahar
    spec:
      containers:
      - name: aahar
        image: ECR_REGISTRY/aahar:IMAGE_TAG
        ports:
        - containerPort: 3000