apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meeting
  template:
    metadata:
      labels:
        app: meeting
    spec:
      containers:
      - name: meeting
        image: ECR_REGISTRY/meeting:IMAGE_TAG
        ports:
        - containerPort: 3000