apiVersion: apps/v1
kind: Deployment
metadata:
  name: ums
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ums
  template:
    metadata:
      labels:
        app: ums
    spec:
      containers:
      - name: ums
        image: <ECR>/ums:latest
        ports:
        - containerPort: 3000